import React from 'react';

export const LANGUAGE_OPTIONS = [
  { value: 'id', label: 'Bahasa Indonesia', icon: <img src="https://flagcdn.com/w40/id.png" alt="ID" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'en', label: 'English', icon: <img src="https://flagcdn.com/w40/gb.png" alt="GB" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'ja', label: '日本語 (Japanese)', icon: <img src="https://flagcdn.com/w40/jp.png" alt="JP" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'ko', label: '한국어 (Korean)', icon: <img src="https://flagcdn.com/w40/kr.png" alt="KR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'zh', label: '中文 (Chinese)', icon: <img src="https://flagcdn.com/w40/cn.png" alt="CN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'fr', label: 'Français (French)', icon: <img src="https://flagcdn.com/w40/fr.png" alt="FR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'de', label: 'Deutsch (German)', icon: <img src="https://flagcdn.com/w40/de.png" alt="DE" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'es', label: 'Español (Spanish)', icon: <img src="https://flagcdn.com/w40/es.png" alt="ES" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'it', label: 'Italiano (Italian)', icon: <img src="https://flagcdn.com/w40/it.png" alt="IT" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'pt', label: 'Português (Portuguese)', icon: <img src="https://flagcdn.com/w40/pt.png" alt="PT" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'ru', label: 'Русский (Russian)', icon: <img src="https://flagcdn.com/w40/ru.png" alt="RU" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'ar', label: 'العربية (Arabic)', icon: <img src="https://flagcdn.com/w40/sa.png" alt="SA" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'hi', label: 'हिन्दी (Hindi)', icon: <img src="https://flagcdn.com/w40/in.png" alt="IN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'bn', label: 'বাংলা (Bengali)', icon: <img src="https://flagcdn.com/w40/bd.png" alt="BD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'pa', label: 'ਪੰਜਾਬੀ (Punjabi)', icon: <img src="https://flagcdn.com/w40/in.png" alt="IN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'te', label: 'తెలుగు (Telugu)', icon: <img src="https://flagcdn.com/w40/in.png" alt="IN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'mr', label: 'मराठी (Marathi)', icon: <img src="https://flagcdn.com/w40/in.png" alt="IN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'ta', label: 'தமிழ் (Tamil)', icon: <img src="https://flagcdn.com/w40/in.png" alt="IN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'ur', label: 'اردو (Urdu)', icon: <img src="https://flagcdn.com/w40/pk.png" alt="PK" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'gu', label: 'ગુજરાતી (Gujarati)', icon: <img src="https://flagcdn.com/w40/in.png" alt="IN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'kn', label: 'ಕನ್ನಡ (Kannada)', icon: <img src="https://flagcdn.com/w40/in.png" alt="IN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'ml', label: 'മലയാളം (Malayalam)', icon: <img src="https://flagcdn.com/w40/in.png" alt="IN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'th', label: 'ไทย (Thai)', icon: <img src="https://flagcdn.com/w40/th.png" alt="TH" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'vi', label: 'Tiếng Việt (Vietnamese)', icon: <img src="https://flagcdn.com/w40/vn.png" alt="VN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'tr', label: 'Türkçe (Turkish)', icon: <img src="https://flagcdn.com/w40/tr.png" alt="TR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'fa', label: 'فارسی (Persian)', icon: <img src="https://flagcdn.com/w40/ir.png" alt="IR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'pl', label: 'Polski (Polish)', icon: <img src="https://flagcdn.com/w40/pl.png" alt="PL" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'uk', label: 'Українська (Ukrainian)', icon: <img src="https://flagcdn.com/w40/ua.png" alt="UA" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'ro', label: 'Română (Romanian)', icon: <img src="https://flagcdn.com/w40/ro.png" alt="RO" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'nl', label: 'Nederlands (Dutch)', icon: <img src="https://flagcdn.com/w40/nl.png" alt="NL" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'sv', label: 'Svenska (Swedish)', icon: <img src="https://flagcdn.com/w40/se.png" alt="SE" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'da', label: 'Dansk (Danish)', icon: <img src="https://flagcdn.com/w40/dk.png" alt="DK" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'fi', label: 'Suomi (Finnish)', icon: <img src="https://flagcdn.com/w40/fi.png" alt="FI" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'no', label: 'Norsk (Norwegian)', icon: <img src="https://flagcdn.com/w40/no.png" alt="NO" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'el', label: 'Ελληνικά (Greek)', icon: <img src="https://flagcdn.com/w40/gr.png" alt="GR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'cs', label: 'Čeština (Czech)', icon: <img src="https://flagcdn.com/w40/cz.png" alt="CZ" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'hu', label: 'Magyar (Hungarian)', icon: <img src="https://flagcdn.com/w40/hu.png" alt="HU" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'he', label: 'עברית (Hebrew)', icon: <img src="https://flagcdn.com/w40/il.png" alt="IL" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'ms', label: 'Bahasa Melayu (Malay)', icon: <img src="https://flagcdn.com/w40/my.png" alt="MY" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'tl', label: 'Tagalog (Filipino)', icon: <img src="https://flagcdn.com/w40/ph.png" alt="PH" className="w-5 h-5 rounded-sm object-cover" /> }
];

export const CURRENCY_OPTIONS = [
  { value: 'IDR', label: 'Rupiah (IDR)', icon: <img src="https://flagcdn.com/w40/id.png" alt="IDR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'USD', label: 'US Dollar (USD)', icon: <img src="https://flagcdn.com/w40/us.png" alt="USD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'EUR', label: 'Euro (EUR)', icon: <img src="https://flagcdn.com/w40/eu.png" alt="EUR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'JPY', label: 'Japanese Yen (JPY)', icon: <img src="https://flagcdn.com/w40/jp.png" alt="JPY" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'GBP', label: 'British Pound (GBP)', icon: <img src="https://flagcdn.com/w40/gb.png" alt="GBP" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'CNY', label: 'Chinese Yuan (CNY)', icon: <img src="https://flagcdn.com/w40/cn.png" alt="CNY" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'KRW', label: 'South Korean Won (KRW)', icon: <img src="https://flagcdn.com/w40/kr.png" alt="KRW" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'MYR', label: 'Malaysian Ringgit (MYR)', icon: <img src="https://flagcdn.com/w40/my.png" alt="MYR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'SGD', label: 'Singapore Dollar (SGD)', icon: <img src="https://flagcdn.com/w40/sg.png" alt="SGD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'AUD', label: 'Australian Dollar (AUD)', icon: <img src="https://flagcdn.com/w40/au.png" alt="AUD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'CAD', label: 'Canadian Dollar (CAD)', icon: <img src="https://flagcdn.com/w40/ca.png" alt="CAD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'CHF', label: 'Swiss Franc (CHF)', icon: <img src="https://flagcdn.com/w40/ch.png" alt="CHF" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'HKD', label: 'Hong Kong Dollar (HKD)', icon: <img src="https://flagcdn.com/w40/hk.png" alt="HKD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'NZD', label: 'New Zealand Dollar (NZD)', icon: <img src="https://flagcdn.com/w40/nz.png" alt="NZD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'SEK', label: 'Swedish Krona (SEK)', icon: <img src="https://flagcdn.com/w40/se.png" alt="SEK" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'NOK', label: 'Norwegian Krone (NOK)', icon: <img src="https://flagcdn.com/w40/no.png" alt="NOK" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'DKK', label: 'Danish Krone (DKK)', icon: <img src="https://flagcdn.com/w40/dk.png" alt="DKK" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'INR', label: 'Indian Rupee (INR)', icon: <img src="https://flagcdn.com/w40/in.png" alt="INR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'RUB', label: 'Russian Ruble (RUB)', icon: <img src="https://flagcdn.com/w40/ru.png" alt="RUB" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'ZAR', label: 'South African Rand (ZAR)', icon: <img src="https://flagcdn.com/w40/za.png" alt="ZAR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'BRL', label: 'Brazilian Real (BRL)', icon: <img src="https://flagcdn.com/w40/br.png" alt="BRL" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'MXN', label: 'Mexican Peso (MXN)', icon: <img src="https://flagcdn.com/w40/mx.png" alt="MXN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'THB', label: 'Thai Baht (THB)', icon: <img src="https://flagcdn.com/w40/th.png" alt="THB" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'PHP', label: 'Philippine Peso (PHP)', icon: <img src="https://flagcdn.com/w40/ph.png" alt="PHP" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'VND', label: 'Vietnamese Dong (VND)', icon: <img src="https://flagcdn.com/w40/vn.png" alt="VND" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'TRY', label: 'Turkish Lira (TRY)', icon: <img src="https://flagcdn.com/w40/tr.png" alt="TRY" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'AED', label: 'UAE Dirham (AED)', icon: <img src="https://flagcdn.com/w40/ae.png" alt="AED" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'SAR', label: 'Saudi Riyal (SAR)', icon: <img src="https://flagcdn.com/w40/sa.png" alt="SAR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'ILS', label: 'Israeli New Shekel (ILS)', icon: <img src="https://flagcdn.com/w40/il.png" alt="ILS" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'PLN', label: 'Polish Zloty (PLN)', icon: <img src="https://flagcdn.com/w40/pl.png" alt="PLN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'CZK', label: 'Czech Koruna (CZK)', icon: <img src="https://flagcdn.com/w40/cz.png" alt="CZK" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'HUF', label: 'Hungarian Forint (HUF)', icon: <img src="https://flagcdn.com/w40/hu.png" alt="HUF" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'RON', label: 'Romanian Leu (RON)', icon: <img src="https://flagcdn.com/w40/ro.png" alt="RON" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'COP', label: 'Colombian Peso (COP)', icon: <img src="https://flagcdn.com/w40/co.png" alt="COP" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'CLP', label: 'Chilean Peso (CLP)', icon: <img src="https://flagcdn.com/w40/cl.png" alt="CLP" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'PEN', label: 'Peruvian Sol (PEN)', icon: <img src="https://flagcdn.com/w40/pe.png" alt="PEN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'ARS', label: 'Argentine Peso (ARS)', icon: <img src="https://flagcdn.com/w40/ar.png" alt="ARS" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'EGP', label: 'Egyptian Pound (EGP)', icon: <img src="https://flagcdn.com/w40/eg.png" alt="EGP" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'NGN', label: 'Nigerian Naira (NGN)', icon: <img src="https://flagcdn.com/w40/ng.png" alt="NGN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'KES', label: 'Kenyan Shilling (KES)', icon: <img src="https://flagcdn.com/w40/ke.png" alt="KES" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'GHS', label: 'Ghanaian Cedi (GHS)', icon: <img src="https://flagcdn.com/w40/gh.png" alt="GHS" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'TWD', label: 'New Taiwan Dollar (TWD)', icon: <img src="https://flagcdn.com/w40/tw.png" alt="TWD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'PKR', label: 'Pakistani Rupee (PKR)', icon: <img src="https://flagcdn.com/w40/pk.png" alt="PKR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'BDT', label: 'Bangladeshi Taka (BDT)', icon: <img src="https://flagcdn.com/w40/bd.png" alt="BDT" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'LKR', label: 'Sri Lankan Rupee (LKR)', icon: <img src="https://flagcdn.com/w40/lk.png" alt="LKR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'MMK', label: 'Myanmar Kyat (MMK)', icon: <img src="https://flagcdn.com/w40/mm.png" alt="MMK" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'KHR', label: 'Cambodian Riel (KHR)', icon: <img src="https://flagcdn.com/w40/kh.png" alt="KHR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'LAK', label: 'Lao Kip (LAK)', icon: <img src="https://flagcdn.com/w40/la.png" alt="LAK" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'BND', label: 'Brunei Dollar (BND)', icon: <img src="https://flagcdn.com/w40/bn.png" alt="BND" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'MOP', label: 'Macanese Pataca (MOP)', icon: <img src="https://flagcdn.com/w40/mo.png" alt="MOP" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'MAD', label: 'Moroccan Dirham (MAD)', icon: <img src="https://flagcdn.com/w40/ma.png" alt="MAD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'DZD', label: 'Algerian Dinar (DZD)', icon: <img src="https://flagcdn.com/w40/dz.png" alt="DZD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'TND', label: 'Tunisian Dinar (TND)', icon: <img src="https://flagcdn.com/w40/tn.png" alt="TND" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'JOD', label: 'Jordanian Dinar (JOD)', icon: <img src="https://flagcdn.com/w40/jo.png" alt="JOD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'LBP', label: 'Lebanese Pound (LBP)', icon: <img src="https://flagcdn.com/w40/lb.png" alt="LBP" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'QAR', label: 'Qatari Riyal (QAR)', icon: <img src="https://flagcdn.com/w40/qa.png" alt="QAR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'KWD', label: 'Kuwaiti Dinar (KWD)', icon: <img src="https://flagcdn.com/w40/kw.png" alt="KWD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'OMR', label: 'Omani Rial (OMR)', icon: <img src="https://flagcdn.com/w40/om.png" alt="OMR" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'BHD', label: 'Bahraini Dinar (BHD)', icon: <img src="https://flagcdn.com/w40/bh.png" alt="BHD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'ISK', label: 'Icelandic Króna (ISK)', icon: <img src="https://flagcdn.com/w40/is.png" alt="ISK" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'HRK', label: 'Croatian Kuna (HRK)', icon: <img src="https://flagcdn.com/w40/hr.png" alt="HRK" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'BGN', label: 'Bulgarian Lev (BGN)', icon: <img src="https://flagcdn.com/w40/bg.png" alt="BGN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'RSD', label: 'Serbian Dinar (RSD)', icon: <img src="https://flagcdn.com/w40/rs.png" alt="RSD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'UAH', label: 'Ukrainian Hryvnia (UAH)', icon: <img src="https://flagcdn.com/w40/ua.png" alt="UAH" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'KZT', label: 'Kazakhstani Tenge (KZT)', icon: <img src="https://flagcdn.com/w40/kz.png" alt="KZT" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'UZS', label: 'Uzbekistani Som (UZS)', icon: <img src="https://flagcdn.com/w40/uz.png" alt="UZS" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'AZN', label: 'Azerbaijani Manat (AZN)', icon: <img src="https://flagcdn.com/w40/az.png" alt="AZN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'GEL', label: 'Georgian Lari (GEL)', icon: <img src="https://flagcdn.com/w40/ge.png" alt="GEL" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'AMD', label: 'Armenian Dram (AMD)', icon: <img src="https://flagcdn.com/w40/am.png" alt="AMD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'BYN', label: 'Belarusian Ruble (BYN)', icon: <img src="https://flagcdn.com/w40/by.png" alt="BYN" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'VEF', label: 'Venezuelan Bolívar (VEF)', icon: <img src="https://flagcdn.com/w40/ve.png" alt="VEF" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'UYU', label: 'Uruguayan Peso (UYU)', icon: <img src="https://flagcdn.com/w40/uy.png" alt="UYU" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'PYG', label: 'Paraguayan Guaraní (PYG)', icon: <img src="https://flagcdn.com/w40/py.png" alt="PYG" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'BOB', label: 'Bolivian Boliviano (BOB)', icon: <img src="https://flagcdn.com/w40/bo.png" alt="BOB" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'CRC', label: 'Costa Rican Colón (CRC)', icon: <img src="https://flagcdn.com/w40/cr.png" alt="CRC" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'PAB', label: 'Panamanian Balboa (PAB)', icon: <img src="https://flagcdn.com/w40/pa.png" alt="PAB" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'DOP', label: 'Dominican Peso (DOP)', icon: <img src="https://flagcdn.com/w40/do.png" alt="DOP" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'GTQ', label: 'Guatemalan Quetzal (GTQ)', icon: <img src="https://flagcdn.com/w40/gt.png" alt="GTQ" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'HNL', label: 'Honduran Lempira (HNL)', icon: <img src="https://flagcdn.com/w40/hn.png" alt="HNL" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'NIO', label: 'Nicaraguan Córdoba (NIO)', icon: <img src="https://flagcdn.com/w40/ni.png" alt="NIO" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'SVC', label: 'Salvadoran Colón (SVC)', icon: <img src="https://flagcdn.com/w40/sv.png" alt="SVC" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'BSD', label: 'Bahamian Dollar (BSD)', icon: <img src="https://flagcdn.com/w40/bs.png" alt="BSD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'BBD', label: 'Barbadian Dollar (BBD)', icon: <img src="https://flagcdn.com/w40/bb.png" alt="BBD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'JMD', label: 'Jamaican Dollar (JMD)', icon: <img src="https://flagcdn.com/w40/jm.png" alt="JMD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'TTD', label: 'Trinidad and Tobago Dollar (TTD)', icon: <img src="https://flagcdn.com/w40/tt.png" alt="TTD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'FJD', label: 'Fijian Dollar (FJD)', icon: <img src="https://flagcdn.com/w40/fj.png" alt="FJD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'PGK', label: 'Papua New Guinean Kina (PGK)', icon: <img src="https://flagcdn.com/w40/pg.png" alt="PGK" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'SBD', label: 'Solomon Islands Dollar (SBD)', icon: <img src="https://flagcdn.com/w40/sb.png" alt="SBD" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'VUV', label: 'Vanuatu Vatu (VUV)', icon: <img src="https://flagcdn.com/w40/vu.png" alt="VUV" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'WST', label: 'Samoan Tala (WST)', icon: <img src="https://flagcdn.com/w40/ws.png" alt="WST" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'TOP', label: 'Tongan Paʻanga (TOP)', icon: <img src="https://flagcdn.com/w40/to.png" alt="TOP" className="w-5 h-5 rounded-sm object-cover" /> },
  { value: 'XPF', label: 'CFP Franc (XPF)', icon: <img src="https://flagcdn.com/w40/pf.png" alt="XPF" className="w-5 h-5 rounded-sm object-cover" /> }
];
